#ifndef COMMANDS_H
#define COMMANDS_H

#define CMD_SET_FREQ_HZ    0xA1
#define CMD_GET_FREQ_HZ    0xB1
#define CMD_SET_CURRENT_UA 0xA2
#define CMD_GET_CURRENT_UA 0xB2
#define CMD_SET_MEASURE_DURATION 0xA3
#define CMD_GET_MEASURE_DURATION 0xB3
#define CMD_START_MEASUREMENT  0xA4
#define CMD_GET_IMPEDANCE  0xB4

#define CMD_ANSWER_GET_FREQ_HZ    0xC1
#define CMD_ANSWER_GET_CURRENT_UA 0xC2
#define CMD_ANSWER_GET_MEASURE_DURATION 0xC3
#define CMD_ANSWER_START_IMPEDANCE  0xC4
#define CMD_ANSWER_GET_IMPEDANCE  0xC5

#define ADMM_ERR 0xFF

#endif /* COMMANDS_H */
